# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='picture',
            field=models.ImageField(null=True, upload_to=b'images/interviews/profile_pictures/'),
        ),
    ]
